version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/tennis-restful

    steps:
    # git pull
    - checkout

    # setup testing env
    - run:
        name: Login to DockerHub
        command: docker login -u $DOCKER_USER -p $DOCKER_PASS

    # Download and cache dependencies
    - restore_cache:
        keys:
        - tennis-restful-{{ checksum "pom.xml" }}

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: tennis-restful-{{ checksum "pom.xml" }}

    # package into a jar
    - run: mvn clean package

    # build and push docker image to docker hub
    - run: $TRIGGER

    # store raw contents of src code
    - store_artifacts:
        path: target/classes
        destination: tennis-restful